run:
  timeout: 5m
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - typecheck
    - ineffassign
    - gofmt
    - goimports

linters-settings:
  govet:
    check-shadowing: false # вместо отдельного параметра 'shadow'

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0